### ISSUE TITLE
Completeion Tracking

### ISSUE THREAD

**Issue by Shrinks99** [Shrinks99/blender-icons#3]
This is a rather crude way of doing it but this screenshot shows what has and hasn't been added yet.  If you're going to add more now you know where to start!

With every PR hopefully we'll cross off some more rows until the process is done, remember to include an updated screenshot to show what you've crossed off :)

![118744276-08256780-b822-11eb-8c51-7f507c4b6954](https://user-images.githubusercontent.com/5672810/118889412-18dde800-b8cb-11eb-86dd-46ff9fbb72ae.png)

**Comment by Songtech-0912** [comment]
Crude, maybe, but seeing as we're 2/7th done we won't have to do this much longer! Even if you have no time to contribute to this, I have been successful in getting 100 icons done at least per day so far, so in less than one week it's done!

**Comment by Shrinks99** [comment]
https://github.com/Shrinks99/blender-icons/pull/4

Updated Image

**Comment by Songtech-0912** [comment]
#5 
Since the set is now complete (at least in terms of the SVGs themselves), let's close this?

**Comment by Shrinks99** [comment]
Yep!  New icons will be dealt with on a per-issue basis.
