### ISSUE TITLE
Request: Blender 4.0 icons

### ISSUE THREAD

**Issue by blender-tv-studio** [Shrinks99/blender-icons#7]
I have a huge add on and I add features all the time and I use your pack all the time but the thing is that when I edit them in Photoshop and like recolor them I compare them to the original blender icons and they're a little bit less resolution I think they upgraded them in the latest version if by any chance you could tell me how you did this because nobody in the world seems to know i'll do it for you and send you the pack so you could upload it here... Otherwise if everything was kept up to date here this would be a really awesome thing it's already cool but I was looking at the icons I imported with the magnifier because I notice they looked a little bit different and you know they just weren't as high resolution...

Here's a free copy of my add on for your troubles it makes everything in blender better... I just added some G P T stuff an assistant that writes code and I'm going full bore into a I now with every sale....... https://drive.google.com/file/d/1MhrD7v3a7ic89VAJcvbSVm4zQN7k7HlX/view?usp=sharing

Just note I always update this thing like all the time so make sure to constantly check the update tab you know like at least a couple times a week...  If you want more information about it it's on blender market it's called FAST studio animation toolz

**Comment by Shrinks99** [comment]
Hi there, thanks for the kind words.

I'm actually thinking of archiving this repo?  It was born out of [this thread](https://devtalk.blender.org/t/splitting-the-icons-svg-file/18937) with most of the actual work being done by @Songtech-0912 who created a script (I think for Inkscape) that cut everything out and saved it to individual files.

The process for updating it would be fairly manual, and I don't really have time to maintain it.  What Blender really needs is a better way of authoring icons, which this does not provide.  Once Blender starts authoring them in a format (Penpot maybe?) that offers batch export for individual icons, it should be trivial to put them into this site so they can be browsed, or perhaps an official Blender one!

> when I edit them in Photoshop and like recolor them I compare them to the original blender icons and they're a little bit less resolution

Photoshop is the wrong tool for the job!  Photoshop is a bitmap image editor, and while it _has tools_ to deal with vector shapes, you should really be using a tool like Inkscape, Illustrator, or Affinity Designer to edit the colours of SVG files and render them to your required resolutions.

**Comment by blender-tv-studio** [comment]
Hey thank you very much for the advice I appreciate it that's really
awesome good thing II have the full Adobe creative suite so that'll be
easy..

**Comment by rodlie** [comment]
> I'm actually thinking of archiving this repo? It was born out of [this thread](https://devtalk.blender.org/t/splitting-the-icons-svg-file/18937) with most of the actual work being done by @Songtech-0912 who created a script (I think for Inkscape) that cut everything out and saved it to individual files.

Just wanted to say that I use several icons (and will use more) from this repo in Friction (https://github.com/friction2d/friction).

https://github.com/friction2d/friction2d.github.io/blob/main/3rdparty/blender.md

**Comment by Songtech-0912** [comment]
@Shrinks99 I'm completely okay with whichever direction you take this repo, just I was looking through blender's build scripts and it appears that the big icons SVG does contain machine-parsable data when paired with the [CMakeLists.txt from here](https://projects.blender.org/blender/blender/src/branch/main/source/blender/editors/datafiles/CMakeLists.txt). I think I might be able to write a script to automatically generate the individual SVG icons rather than redoing the manual process we used. You think that's worth looking into?

**Comment by Shrinks99** [comment]
I sent an email to Dalai Felintino from Blender asking about this, he's given presentations & written about Blender's use of Penpot in the past and I think the core devs are transitioning to using it for more design work internally.

If there's interest in some help moving everything into a nice Penpot file where things can be exported en-masse, I'd be willing to help them sort that out this week.  If not, perhaps your solution is the best one @Songtech-0912.

Either way, it's gotta be automated, I just figure why not try and go to the root of the problem first and work backwards from there :)

**Comment by Shrinks99** [comment]
Received a nice response!  Blender maintains their own icon site and maybe has this whole time?!  Go check it out!  https://ui.blender.org/icons

Given that, probably best if I archive this repo and link to that in the readme?

**Comment by rodlie** [comment]
Nice, didn't know about that.

**Comment by blender-tv-studio** [comment]
Very cool! You know what somebody should do. I'll do it if nobody takes
this in contact the makers of the development icon default blender add-on
and have them integrate this as an extra button into their add-ons so you
could just open it up from within the interface...
